[package]
name = "tcpChat"
version = "1.0.0"
edition = "2021"
description = "Simple chatroom over tcp/ip"
license = "MIT"
authors = ["itsgerliz"]

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }

[profile.release-stripped]
inherits = "release"
strip = true